"""Added status for image upload

Revision ID: a8790ba17bc3
Revises: 7ed360ba684d
Create Date: 2025-02-21 20:34:47.890600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8790ba17bc3'
down_revision: Union[str, None] = '7ed360ba684d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images',  sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='processingstatus'), nullable=False),)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'status')
    # ### end Alembic commands ###
